### ISSUE TITLE
`cov(::Adjoint, ::Weights)` is wrong

### ISSUE THREAD

**Issue by yha** [JuliaLang/Statistics.jl#82] opened 2021-07-26 23:11 UTC
```
julia> x = reshape(1:6,2,3)
2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6

julia> cov(x'; corrected=false)
2×2 Matrix{Float64}:
 2.66667  2.66667
 2.66667  2.66667

julia> cov(x', Weights([1,1,1]))  # Wrong
2×1 Matrix{Float64}:
 0.0
 0.0

julia> cov(Matrix(x'), Weights([1,1,1]))  # correct
2×2 Matrix{Float64}:
 2.66667  2.66667
 2.66667  2.66667

julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by nalimilan** [comment] 2021-08-17 10:27
This is a bad interaction between Statistics and StatsBase. In Statistics, `cov(X, Y)` takes the covariance between `X` and `Y`. In StatsBase, `cov(X, w)` takes the weighted covariance of `X` with itself using weights `w`. Unfortunately, in some cases it's ambiguous which method you can to call, and Julia ends up calling the former or the latter depending on which method signatures are more specific.

The solution is to use a `weights` keyword argument instead.

Closing as a duplicate of https://github.com/JuliaStats/StatsBase.jl/issues/409. The bug is in StatsBase, not in Statistics.

**Closed by nalimilan** 2021-08-17 10:27 UTC
